openapi: 3.0.1
info:
  title: Product API
  version: '1.0'
servers:
  - url: https://ipaas-retail.azure-api.net/product
paths:
  /Product:
    get:
      tags:
        - Product
      summary: GetProducts
      operationId: GetProducts
      responses:
        '200':
          description: Success
          content:
            application/json;odata.metadata=minimal;odata.streaming=true:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                - productId: 0
                  productName: string
                  category: string
                  listPrice: 0
            application/json;odata.metadata=minimal;odata.streaming=false:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                - productId: 0
                  productName: string
                  category: string
                  listPrice: 0
            application/json;odata.metadata=minimal:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                - productId: 0
                  productName: string
                  category: string
                  listPrice: 0
            application/json;odata.metadata=full;odata.streaming=true:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                - productId: 0
                  productName: string
                  category: string
                  listPrice: 0
            application/json;odata.metadata=full;odata.streaming=false:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                - productId: 0
                  productName: string
                  category: string
                  listPrice: 0
            application/json;odata.metadata=full:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                - productId: 0
                  productName: string
                  category: string
                  listPrice: 0
            application/json;odata.metadata=none;odata.streaming=true:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                - productId: 0
                  productName: string
                  category: string
                  listPrice: 0
            application/json;odata.metadata=none;odata.streaming=false:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                - productId: 0
                  productName: string
                  category: string
                  listPrice: 0
            application/json;odata.metadata=none:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                - productId: 0
                  productName: string
                  category: string
                  listPrice: 0
            application/json;odata.streaming=true:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                - productId: 0
                  productName: string
                  category: string
                  listPrice: 0
            application/json;odata.streaming=false:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                - productId: 0
                  productName: string
                  category: string
                  listPrice: 0
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                - productId: 0
                  productName: string
                  category: string
                  listPrice: 0
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example: <ApiProductGet200ApplicationXmlResponse> <productId>0</productId> <productName>string</productName> <category>string</category> <listPrice>0</listPrice> </ApiProductGet200ApplicationXmlResponse>
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                default:
                  value: 
            application/octet-stream:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                default:
                  value: 
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                - productId: 0
                  productName: string
                  category: string
                  listPrice: 0
components:
  schemas:
    DiscountedProduct:
      type: object
      properties:
        productId:
          type: integer
          format: int32
          nullable: true
        discountPrice:
          type: number
          format: double
          nullable: true
        priceValidUntil:
          type: string
          format: date-time
          nullable: true
      additionalProperties: false
    OverwriteBusinessLogic:
      type: object
      properties:
        overwriteBusinessLogicId:
          type: integer
          format: int32
        storeId:
          type: integer
          format: int32
        action:
          type: string
          nullable: true
        date:
          type: string
          format: date-time
        openHours:
          type: string
          nullable: true
        comment:
          type: string
          nullable: true
      additionalProperties: false
    Product:
      type: object
      properties:
        productId:
          type: integer
          format: int32
          nullable: true
        productName:
          type: string
          nullable: true
        category:
          type: string
          nullable: true
        listPrice:
          type: number
          format: double
          nullable: true
      additionalProperties: false
    Store:
      type: object
      properties:
        storeId:
          type: integer
          format: int32
        storeName:
          type: string
          nullable: true
        canton:
          type: string
          nullable: true
        streeet:
          type: string
          nullable: true
        plz:
          type: integer
          format: int32
        city:
          type: string
          nullable: true
        storeType:
          type: string
          nullable: true
        weekKalendarId:
          type: integer
          format: int32
      additionalProperties: false
    StoreCalendar:
      type: object
      properties:
        storeId:
          type: integer
          format: int32
        date:
          type: string
          format: date-time
          nullable: true
        opening:
          type: string
          nullable: true
        dayType:
          type: string
          nullable: true
        reason:
          type: string
          nullable: true
        comment:
          type: string
          nullable: true
      additionalProperties: false
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]